### ISSUE TITLE
Horizontal gradient for AppBar 

### ISSUE THREAD

**Issue by LokiRathod** [joostlek/GradientAppBar#4]
Hi
I was looking for the horizontal color gradients for the AppBar.
Is there, any way i can do it by using this lib...?

**Comment by joostlek** [comment]
Hey,
Do you mean the same as in the image but turned 90 degrees?

**Comment by D4ddy-LiLd4rk** [comment]
> Hey,
> Do you mean the same as in the image but turned 90 degrees?

That's what I am looking for. I could imagine another attribute to assign the gradient for "top-down", "left-right", "down-top" and "right-left. Never the less I only need top-down.

**Comment by joostlek** [comment]
I think a number with the amount of degrees would be better, I'll look into it

**Comment by sgruhier** [comment]
I think if `Gradient` is more customisable (https://github.com/joostlek/GradientAppBar/blob/master/lib/gradient_app_bar.dart#L473) it will be nice
Right now only 2 colors are taken from parameters everything else is hardcoded

```dart
              gradient: LinearGradient(
                  colors: [
                    widget.backgroundColorStart ?? themeData.primaryColor,
                    widget.backgroundColorEnd ?? themeData.accentColor,
                  ],
                  begin: FractionalOffset(0.0, 0.0),
                  end: FractionalOffset(1.0, 0.0),
                  stops: [0.0, 1.0],
                  tileMode: TileMode.clamp),
            ),
```

**Comment by joostlek** [comment]
That's right, but it would be better to support a nice and clean way to do it, I would need to think of one, but I am currently a bit busy, but it's on my to-do list

**Comment by LokiRathod** [comment]
Hi this, how i did it.

appBar: AppBar(
        title: Text(
          Constants.appName,
          style: TextStyle(fontSize: 16.0, fontWeight: FontWeight.bold),
        ),
        centerTitle: true,
        flexibleSpace: Container(
          decoration: new BoxDecoration(
            gradient: new LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [color1, color2],
                tileMode: TileMode.clamp),
          ),
        ),
      ),

color1 and color2 is whatever user gives as color code.

**Comment by joostlek** [comment]
But it would be awesome to also support custom stops, I'll have more time soon to do that

**Comment by joostlek** [comment]
I released an update where you can use your own gradient. So you could do:

`Scaffold(
        appBar: GradientAppBar(
          title: Text(widget.title),
          gradient: new LinearGradient(
begin: Alignment.topCenter,
end: Alignment.bottomCenter,
colors: [color1, color2],
tileMode: TileMode.clamp),
          bottom: TabBar(tabs: <Widget>[
            Tab(
              icon: Icon(Icons.home),
              text: 'Home',
            ),
            Tab(
              icon: Icon(Icons.store),
              text: 'Store',
            )
          ]),
        ),`
